const card1 = [image1, image2, image3, image4, image5, image6, image7, image8, image9, image10, image11, image12];
const card2 = [imagep1, imagep2, imagep3, imagep4, imagep5, imagep6, imagep7, imagep8, imagep9, imagep10, imagep11, imagep12];

//Imágenes del nivel
const image1 = newImage();
const image2 = newImage();
const image3 = newImage();
const image4 = newImage();
const image5 = newImage();
const image6 = newImage();
const image7 = newImage();
const image8 = newImage();
const image9 = newImage();
const image10 = newImage();
const image11 = newImage();
const image12 = newImage();
//Parejas de Imágenes
const imagep1 = newImage();
const imagep2 = newImage();
const imagep3 = newImage();
const imagep4 = newImage();
const imagep5 = newImage();
const imagep6 = newImage();
const imagep7 = newImage();
const imagep8 = newImage();
const imagep9 = newImage();
const imagep10 = newImage();
const imagep11 = newImage();
const imagep12 = newImage();

//Imagenes
image1.src = "1.png";
image2.src = "2.png";
image3.src = "3.png"; 
image4.src = "4.png";
image5.src = "5.png";
image6.src = "6.png";
image7.src = "7.png";
image8.src = "8.png"; 
image9.src = "9.png";
image10.src = "10.png";
image11.src = "11.png";
image12.src = "12.png";

//Las parejas
imagep1.src = "1.png";
imagep2.src = "2.png";
imagep3.src = "3.png"; 
imagep4.src = "4.png";
imagep5.src = "5.png";
imagep6.src = "6.png";
imagep7.src = "7.png";
imagep8.src = "8.png"; 
imagep9.src = "9.png";
imagep10.src = "10.png";
imagep11.src = "11.png";
imagep12.src = "12.png";

console.log(here in 'CONSTANTESFF.JS');